# visa_checklists.py
"""
Germaniya elchixonasiga topshiriladigan hujjatlar ro'yxati,
viza turlari bo'yicha. Bu ro'yxatlar umumiy ma'lumot sifatida
beriladi — har doim elchixonaning rasmiy saytidan tekshirib chiqish kerak,
chunki talablar vaqti-vaqti bilan o'zgaradi.
"""

CHECKLISTS = {
    "student": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa, imzolangan)",
            "Xalqaro pasport (kamida 2 bo'sh sahifa, amal qilish muddati 1 yildan ortiq)",
            "2 dona biometrik fotosurat (35x45mm, oq fon)",
            "Universitetdan qabul xati (Zulassungsbescheid)",
            "Tasdiqlangan Lebenslauf (Europass formatida, nemis/ingliz tilida)",
            "Motivatsion xat (Motivationsschreiben)",
            "Til sertifikati (TestDaF, DSH, IELTS yoki TOEFL — dasturga qarab)",
            "Diplom va attestat nusxalari + nemis/ingliz tiliga tarjimasi",
            "Moliyaviy ta'minot isboti (Sperrkonto — kamida 11,904 EUR yillik, 2024 ko'rsatkichi, yangilanishini tekshiring)",
            "Tibbiy sug'urta polisi",
            "Yashash joyi haqida ma'lumot (agar mavjud bo'lsa)",
            "Viza yig'imini to'lash kvitansiyasi",
        ],
        "ru": [
            "Заполненная анкета на визу (2 экземпляра, с подписью)",
            "Загранпаспорт (минимум 2 пустые страницы, срок действия 1+ год)",
            "2 биометрических фото (35x45мм, белый фон)",
            "Письмо о зачислении из университета (Zulassungsbescheid)",
            "Lebenslauf (резюме в формате Europass, на нем./англ. языке)",
            "Мотивационное письмо (Motivationsschreiben)",
            "Сертификат языка (TestDaF, DSH, IELTS или TOEFL — зависит от программы)",
            "Копии диплома и аттестата + перевод на нем./англ. язык",
            "Подтверждение финансового обеспечения (Sperrkonto — от 11,904 EUR в год, проверьте актуальную сумму)",
            "Медицинская страховка",
            "Подтверждение места проживания (если есть)",
            "Квитанция об оплате visa-сбора",
        ],
        "en": [
            "Completed visa application form (2 copies, signed)",
            "Valid passport (at least 2 blank pages, valid 1+ year)",
            "2 biometric photos (35x45mm, white background)",
            "University admission letter (Zulassungsbescheid)",
            "Lebenslauf (CV in Europass format, German/English)",
            "Motivation letter (Motivationsschreiben)",
            "Language certificate (TestDaF, DSH, IELTS or TOEFL depending on program)",
            "Diploma and transcripts + certified translation to German/English",
            "Proof of financial resources (Sperrkonto — currently ~11,904 EUR/year, verify current amount)",
            "Health insurance certificate",
            "Proof of accommodation (if available)",
            "Visa fee payment receipt",
        ],
    },
    "ausbildung": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa)",
            "Xalqaro pasport",
            "2 dona biometrik fotosurat",
            "Ausbildung shartnomasi (Ausbildungsvertrag)",
            "Lebenslauf (Europass formatida)",
            "Motivatsion xat",
            "Nemis tili sertifikati (odatda B1 yoki A2+B1 va'da xati)",
            "Diplom va attestat + tarjima",
            "Moliyaviy ta'minot isboti (Sperrkonto yoki kafillik xati)",
            "Tibbiy sug'urta",
            "Viza yig'imi kvitansiyasi",
        ],
        "ru": [
            "Анкета на визу (2 экземпляра)",
            "Загранпаспорт",
            "2 биометрических фото",
            "Договор о профессиональном обучении (Ausbildungsvertrag)",
            "Lebenslauf (Europass формат)",
            "Мотивационное письмо",
            "Сертификат немецкого языка (обычно B1)",
            "Диплом и аттестат + перевод",
            "Подтверждение финансов (Sperrkonto или письмо-гарантия)",
            "Медицинская страховка",
            "Квитанция об оплате визового сбора",
        ],
        "en": [
            "Visa application form (2 copies)",
            "Valid passport",
            "2 biometric photos",
            "Vocational training contract (Ausbildungsvertrag)",
            "Lebenslauf (Europass format)",
            "Motivation letter",
            "German language certificate (usually B1)",
            "Diploma and transcripts + translation",
            "Proof of financial resources (Sperrkonto or sponsorship letter)",
            "Health insurance",
            "Visa fee payment receipt",
        ],
    },
    "work": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa)",
            "Xalqaro pasport",
            "2 dona biometrik fotosurat",
            "Ish shartnomasi yoki taklifnoma (Arbeitsvertrag)",
            "Federal Mehnat Agentligi roziligi (agar talab qilinsa)",
            "Lebenslauf (Europass formatida)",
            "Motivatsion xat",
            "Malaka/diplomlarni tan olish hujjati (agar tartibga solinadigan kasb bo'lsa)",
            "Diplom va sertifikatlar + tarjima",
            "Tibbiy sug'urta",
            "Viza yig'imi kvitansiyasi",
        ],
        "ru": [
            "Анкета на визу (2 экземпляра)",
            "Загранпаспорт",
            "2 биометрических фото",
            "Трудовой договор или предложение о работе (Arbeitsvertrag)",
            "Одобрение от Агентства по труду (если требуется)",
            "Lebenslauf (Europass формат)",
            "Мотивационное письмо",
            "Подтверждение признания квалификации (для регулируемых профессий)",
            "Диплом и сертификаты + перевод",
            "Медицинская страховка",
            "Квитанция об оплате визового сбора",
        ],
        "en": [
            "Visa application form (2 copies)",
            "Valid passport",
            "2 biometric photos",
            "Employment contract or job offer (Arbeitsvertrag)",
            "Federal Employment Agency approval (if required)",
            "Lebenslauf (Europass format)",
            "Motivation letter",
            "Recognition of qualifications (for regulated professions)",
            "Diploma and certificates + translation",
            "Health insurance",
            "Visa fee payment receipt",
        ],
    },
    "job_seeker": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa)",
            "Xalqaro pasport",
            "2 dona biometrik fotosurat",
            "Diplom (Germaniyada tan olinishi shart, kamida 5 ball — Chancenkarte tizimi)",
            "Lebenslauf (Europass formatida)",
            "Motivatsion xat",
            "Til sertifikati (nemis A1 yoki ingliz B2 — Chancenkarte talabi)",
            "Moliyaviy ta'minot isboti (Sperrkonto)",
            "Tibbiy sug'urta",
            "Viza yig'imi kvitansiyasi",
        ],
        "ru": [
            "Анкета на визу (2 экземпляра)",
            "Загранпаспорт",
            "2 биометрических фото",
            "Диплом (должен быть признан в Германии, мин. 5 баллов по системе Chancenkarte)",
            "Lebenslauf (Europass формат)",
            "Мотивационное письмо",
            "Языковой сертификат (немецкий A1 или английский B2 — требование Chancenkarte)",
            "Подтверждение финансов (Sperrkonto)",
            "Медицинская страховка",
            "Квитанция об оплате визового сбора",
        ],
        "en": [
            "Visa application form (2 copies)",
            "Valid passport",
            "2 biometric photos",
            "Degree/diploma (must be recognized in Germany, min. 5 points under Chancenkarte system)",
            "Lebenslauf (Europass format)",
            "Motivation letter",
            "Language certificate (German A1 or English B2 — Chancenkarte requirement)",
            "Proof of financial resources (Sperrkonto)",
            "Health insurance",
            "Visa fee payment receipt",
        ],
    },
    "family": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa)",
            "Xalqaro pasport",
            "2 dona biometrik fotosurat",
            "Nikoh/tug'ilganlik guvohnomasi (apostil va tarjima bilan)",
            "Germaniyadagi oila a'zosining hujjatlari (passport, ro'yxatga olinish, ish/daromad isboti)",
            "Nemis tili sertifikati (odatda A1 daraja, ba'zi holatlarda talab qilinmaydi)",
            "Tibbiy sug'urta",
            "Viza yig'imi kvitansiyasi",
        ],
        "ru": [
            "Анкета на визу (2 экземпляра)",
            "Загранпаспорт",
            "2 биометрических фото",
            "Свидетельство о браке/рождении (с апостилем и переводом)",
            "Документы члена семьи в Германии (паспорт, регистрация, подтверждение дохода)",
            "Сертификат немецкого языка (обычно A1, в некоторых случаях не требуется)",
            "Медицинская страховка",
            "Квитанция об оплате визового сбора",
        ],
        "en": [
            "Visa application form (2 copies)",
            "Valid passport",
            "2 biometric photos",
            "Marriage/birth certificate (apostilled and translated)",
            "Documents of family member in Germany (passport, registration, proof of income)",
            "German language certificate (usually A1, sometimes waived)",
            "Health insurance",
            "Visa fee payment receipt",
        ],
    },
}


def get_checklist(visa_type: str, lang: str) -> list[str]:
    """Berilgan viza turi va til uchun hujjatlar ro'yxatini qaytaradi."""
    return CHECKLISTS.get(visa_type, {}).get(lang, CHECKLISTS.get(visa_type, {}).get("en", []))
