# visa_checklists.py
"""
Germaniya elchixonasiga topshiriladigan hujjatlar ro'yxati,
viza turlari bo'yicha. Bu ro'yxatlar umumiy ma'lumot sifatida
beriladi — har doim elchixonaning rasmiy saytidan tekshirib chiqish kerak,
chunki talablar vaqti-vaqti bilan o'zgaradi.
"""

CHECKLISTS = {
    "student": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa, imzolangan)",
            "Xalqaro pasport (kamida 2 bo'sh sahifa, amal qilish muddati 1 yildan ortiq)",
            "2 dona biometrik fotosurat (35x45mm, oq fon)",
            "Universitetdan qabul xati (Zulassungsbescheid)",
            "Tasdiqlangan Lebenslauf (Europass formatida, nemis/ingliz tilida)",
            "Motivatsion xat (Motivationsschreiben)",
            "Til sertifikati (TestDaF, DSH, IELTS yoki TOEFL — dasturga qarab)",
            "Diplom va attestat nusxalari + nemis/ingliz tiliga tarjimasi",
            "Moliyaviy ta'minot isboti (Sperrkonto — kamida 11,904 EUR yillik, 2024 ko'rsatkichi, yangilanishini tekshiring)",
            "Tibbiy sug'urta polisi",
            "Yashash joyi haqida ma'lumot (agar mavjud bo'lsa)",
            "Viza yig'imini to'lash kvitansiyasi",
        ],
        "ru": [
            "Заполненная анкета на визу (2 экземпляра, с подписью)",
            "Загранпаспорт (минимум 2 пустые страницы, срок действия 1+ год)",
            "2 биометрических фото (35x45мм, белый фон)",
            "Письмо о зачислении из университета (Zulassungsbescheid)",
            "Lebenslauf (резюме в формате Europass, на нем./англ. языке)",
            "Мотивационное письмо (Motivationsschreiben)",
            "Сертификат языка (TestDaF, DSH, IELTS или TOEFL — зависит от программы)",
            "Копии диплома и аттестата + перевод на нем./англ. язык",
            "Подтверждение финансового обеспечения (Sperrkonto — от 11,904 EUR в год, проверьте актуальную сумму)",
            "Медицинская страховка",
            "Подтверждение места проживания (если есть)",
            "Квитанция об оплате visa-сбора",
        ],
        "en": [
            "Completed visa application form (2 copies, signed)",
            "Valid passport (at least 2 blank pages, valid 1+ year)",
            "2 biometric photos (35x45mm, white background)",
            "University admission letter (Zulassungsbescheid)",
            "Lebenslauf (CV in Europass format, German/English)",
            "Motivation letter (Motivationsschreiben)",
            "Language certificate (TestDaF, DSH, IELTS or TOEFL depending on program)",
            "Diploma and transcripts + certified translation to German/English",
            "Proof of financial resources (Sperrkonto — currently ~11,904 EUR/year, verify current amount)",
            "Health insurance certificate",
            "Proof of accommodation (if available)",
            "Visa fee payment receipt",
        ],
        "tr": [
            "Doldurulmuş vize başvuru formu (2 nüsha, imzalı)",
            "Geçerli pasaport (en az 2 boş sayfa, 1+ yıl geçerlilik süresi)",
            "2 biyometrik fotoğraf (35x45mm, beyaz arka plan)",
            "Üniversite kabul mektubu (Zulassungsbescheid)",
            "Lebenslauf (Europass formatında CV, Almanca/İngilizce)",
            "Motivasyon mektubu (Motivationsschreiben)",
            "Dil sertifikası (programa göre TestDaF, DSH, IELTS veya TOEFL)",
            "Diploma ve transkriptler + Almanca/İngilizce onaylı tercüme",
            "Mali yeterlilik kanıtı (Sperrkonto — şu anda yaklaşık 11.904 EUR/yıl, güncel tutarı kontrol edin)",
            "Sağlık sigortası belgesi",
            "Konaklama kanıtı (varsa)",
            "Vize ücreti ödeme makbuzu",
        ],
        "es": [
            "Formulario de solicitud de visa completado (2 copias, firmado)",
            "Pasaporte válido (al menos 2 páginas en blanco, válido por 1+ año)",
            "2 fotos biométricas (35x45mm, fondo blanco)",
            "Carta de admisión universitaria (Zulassungsbescheid)",
            "Lebenslauf (CV en formato Europass, alemán/inglés)",
            "Carta de motivación (Motivationsschreiben)",
            "Certificado de idioma (TestDaF, DSH, IELTS o TOEFL según el programa)",
            "Diploma y expedientes académicos + traducción certificada al alemán/inglés",
            "Comprobante de recursos financieros (Sperrkonto — actualmente ~11.904 EUR/año, verifica el monto actual)",
            "Certificado de seguro médico",
            "Comprobante de alojamiento (si está disponible)",
            "Recibo de pago de la tasa de visa",
        ],
        "hi": [
            "पूर्ण वीज़ा आवेदन फ़ॉर्म (2 प्रतियां, हस्ताक्षरित)",
            "मान्य पासपोर्ट (कम से कम 2 खाली पृष्ठ, 1+ वर्ष वैधता)",
            "2 बायोमेट्रिक फ़ोटो (35x45mm, सफ़ेद बैकग्राउंड)",
            "विश्वविद्यालय प्रवेश पत्र (Zulassungsbescheid)",
            "Lebenslauf (Europass फॉर्मेट में CV, जर्मन/अंग्रेज़ी)",
            "प्रेरणा पत्र (Motivationsschreiben)",
            "भाषा प्रमाणपत्र (कार्यक्रम के अनुसार TestDaF, DSH, IELTS या TOEFL)",
            "डिप्लोमा और ट्रांसक्रिप्ट + जर्मन/अंग्रेज़ी में प्रमाणित अनुवाद",
            "वित्तीय संसाधनों का प्रमाण (Sperrkonto — वर्तमान में ~11,904 EUR/वर्ष, वर्तमान राशि सत्यापित करें)",
            "स्वास्थ्य बीमा प्रमाणपत्र",
            "आवास का प्रमाण (यदि उपलब्ध हो)",
            "वीज़ा शुल्क भुगतान रसीद",
        ],
        "uk": [
            "Заповнена анкета на візу (2 копії, з підписом)",
            "Дійсний паспорт (мінімум 2 порожні сторінки, термін дії 1+ рік)",
            "2 біометричних фото (35x45мм, білий фон)",
            "Лист про зарахування з університету (Zulassungsbescheid)",
            "Lebenslauf (резюме у форматі Europass, нім./англ. мовою)",
            "Мотиваційний лист (Motivationsschreiben)",
            "Сертифікат мови (TestDaF, DSH, IELTS або TOEFL — залежно від програми)",
            "Копії диплома та атестата + переклад нім./англ. мовою",
            "Підтвердження фінансового забезпечення (Sperrkonto — від 11 904 EUR на рік, перевірте актуальну суму)",
            "Медичне страхування",
            "Підтвердження місця проживання (якщо є)",
            "Квитанція про оплату візового збору",
        ],
    },
    "ausbildung": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa)",
            "Xalqaro pasport",
            "2 dona biometrik fotosurat",
            "Ausbildung shartnomasi (Ausbildungsvertrag)",
            "Lebenslauf (Europass formatida)",
            "Motivatsion xat",
            "Nemis tili sertifikati (odatda B1 yoki A2+B1 va'da xati)",
            "Diplom va attestat + tarjima",
            "Moliyaviy ta'minot isboti (Sperrkonto yoki kafillik xati)",
            "Tibbiy sug'urta",
            "Viza yig'imi kvitansiyasi",
        ],
        "ru": [
            "Анкета на визу (2 экземпляра)",
            "Загранпаспорт",
            "2 биометрических фото",
            "Договор о профессиональном обучении (Ausbildungsvertrag)",
            "Lebenslauf (Europass формат)",
            "Мотивационное письмо",
            "Сертификат немецкого языка (обычно B1)",
            "Диплом и аттестат + перевод",
            "Подтверждение финансов (Sperrkonto или письмо-гарантия)",
            "Медицинская страховка",
            "Квитанция об оплате визового сбора",
        ],
        "en": [
            "Visa application form (2 copies)",
            "Valid passport",
            "2 biometric photos",
            "Vocational training contract (Ausbildungsvertrag)",
            "Lebenslauf (Europass format)",
            "Motivation letter",
            "German language certificate (usually B1)",
            "Diploma and transcripts + translation",
            "Proof of financial resources (Sperrkonto or sponsorship letter)",
            "Health insurance",
            "Visa fee payment receipt",
        ],
        "tr": [
            "Vize başvuru formu (2 nüsha)",
            "Geçerli pasaport",
            "2 biyometrik fotoğraf",
            "Mesleki eğitim sözleşmesi (Ausbildungsvertrag)",
            "Lebenslauf (Europass formatı)",
            "Motivasyon mektubu",
            "Almanca dil sertifikası (genellikle B1)",
            "Diploma ve transkriptler + tercüme",
            "Mali yeterlilik kanıtı (Sperrkonto veya sponsorluk mektubu)",
            "Sağlık sigortası",
            "Vize ücreti ödeme makbuzu",
        ],
        "es": [
            "Formulario de solicitud de visa (2 copias)",
            "Pasaporte válido",
            "2 fotos biométricas",
            "Contrato de formación profesional (Ausbildungsvertrag)",
            "Lebenslauf (formato Europass)",
            "Carta de motivación",
            "Certificado de alemán (normalmente B1)",
            "Diploma y expedientes + traducción",
            "Comprobante de recursos financieros (Sperrkonto o carta de patrocinio)",
            "Seguro médico",
            "Recibo de pago de la tasa de visa",
        ],
        "hi": [
            "वीज़ा आवेदन फ़ॉर्म (2 प्रतियां)",
            "मान्य पासपोर्ट",
            "2 बायोमेट्रिक फ़ोटो",
            "व्यावसायिक प्रशिक्षण अनुबंध (Ausbildungsvertrag)",
            "Lebenslauf (Europass फॉर्मेट)",
            "प्रेरणा पत्र",
            "जर्मन भाषा प्रमाणपत्र (सामान्यतः B1)",
            "डिप्लोमा और ट्रांसक्रिप्ट + अनुवाद",
            "वित्तीय संसाधनों का प्रमाण (Sperrkonto या प्रायोजन पत्र)",
            "स्वास्थ्य बीमा",
            "वीज़ा शुल्क भुगतान रसीद",
        ],
        "uk": [
            "Анкета на візу (2 копії)",
            "Дійсний паспорт",
            "2 біометричних фото",
            "Договір про професійне навчання (Ausbildungsvertrag)",
            "Lebenslauf (формат Europass)",
            "Мотиваційний лист",
            "Сертифікат німецької мови (зазвичай B1)",
            "Диплом та атестат + переклад",
            "Підтвердження фінансів (Sperrkonto або гарантійний лист)",
            "Медичне страхування",
            "Квитанція про оплату візового збору",
        ],
    },
    "work": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa)",
            "Xalqaro pasport",
            "2 dona biometrik fotosurat",
            "Ish shartnomasi yoki taklifnoma (Arbeitsvertrag)",
            "Federal Mehnat Agentligi roziligi (agar talab qilinsa)",
            "Lebenslauf (Europass formatida)",
            "Motivatsion xat",
            "Malaka/diplomlarni tan olish hujjati (agar tartibga solinadigan kasb bo'lsa)",
            "Diplom va sertifikatlar + tarjima",
            "Tibbiy sug'urta",
            "Viza yig'imi kvitansiyasi",
        ],
        "ru": [
            "Анкета на визу (2 экземпляра)",
            "Загранпаспорт",
            "2 биометрических фото",
            "Трудовой договор или предложение о работе (Arbeitsvertrag)",
            "Одобрение от Агентства по труду (если требуется)",
            "Lebenslauf (Europass формат)",
            "Мотивационное письмо",
            "Подтверждение признания квалификации (для регулируемых профессий)",
            "Диплом и сертификаты + перевод",
            "Медицинская страховка",
            "Квитанция об оплате визового сбора",
        ],
        "en": [
            "Visa application form (2 copies)",
            "Valid passport",
            "2 biometric photos",
            "Employment contract or job offer (Arbeitsvertrag)",
            "Federal Employment Agency approval (if required)",
            "Lebenslauf (Europass format)",
            "Motivation letter",
            "Recognition of qualifications (for regulated professions)",
            "Diploma and certificates + translation",
            "Health insurance",
            "Visa fee payment receipt",
        ],
        "tr": [
            "Vize başvuru formu (2 nüsha)",
            "Geçerli pasaport",
            "2 biyometrik fotoğraf",
            "İş sözleşmesi veya iş teklifi (Arbeitsvertrag)",
            "Federal İstihdam Ajansı onayı (gerekirse)",
            "Lebenslauf (Europass formatı)",
            "Motivasyon mektubu",
            "Yeterlilik tanıma belgesi (düzenlenmiş mesleklerde)",
            "Diploma ve sertifikalar + tercüme",
            "Sağlık sigortası",
            "Vize ücreti ödeme makbuzu",
        ],
        "es": [
            "Formulario de solicitud de visa (2 copias)",
            "Pasaporte válido",
            "2 fotos biométricas",
            "Contrato de trabajo u oferta de empleo (Arbeitsvertrag)",
            "Aprobación de la Agencia Federal de Empleo (si se requiere)",
            "Lebenslauf (formato Europass)",
            "Carta de motivación",
            "Reconocimiento de cualificaciones (para profesiones reguladas)",
            "Diploma y certificados + traducción",
            "Seguro médico",
            "Recibo de pago de la tasa de visa",
        ],
        "hi": [
            "वीज़ा आवेदन फ़ॉर्म (2 प्रतियां)",
            "मान्य पासपोर्ट",
            "2 बायोमेट्रिक फ़ोटो",
            "रोज़गार अनुबंध या नौकरी की पेशकश (Arbeitsvertrag)",
            "फ़ेडरल एम्प्लॉयमेंट एजेंसी की मंज़ूरी (यदि आवश्यक हो)",
            "Lebenslauf (Europass फॉर्मेट)",
            "प्रेरणा पत्र",
            "योग्यता मान्यता दस्तावेज़ (विनियमित व्यवसायों के लिए)",
            "डिप्लोमा और प्रमाणपत्र + अनुवाद",
            "स्वास्थ्य बीमा",
            "वीज़ा शुल्क भुगतान रसीद",
        ],
        "uk": [
            "Анкета на візу (2 копії)",
            "Дійсний паспорт",
            "2 біометричних фото",
            "Трудовий договір або пропозиція роботи (Arbeitsvertrag)",
            "Схвалення Федерального агентства праці (якщо потрібно)",
            "Lebenslauf (формат Europass)",
            "Мотиваційний лист",
            "Підтвердження визнання кваліфікації (для регульованих професій)",
            "Диплом та сертифікати + переклад",
            "Медичне страхування",
            "Квитанція про оплату візового збору",
        ],
    },
    "job_seeker": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa)",
            "Xalqaro pasport",
            "2 dona biometrik fotosurat",
            "Diplom (Germaniyada tan olinishi shart, kamida 5 ball — Chancenkarte tizimi)",
            "Lebenslauf (Europass formatida)",
            "Motivatsion xat",
            "Til sertifikati (nemis A1 yoki ingliz B2 — Chancenkarte talabi)",
            "Moliyaviy ta'minot isboti (Sperrkonto)",
            "Tibbiy sug'urta",
            "Viza yig'imi kvitansiyasi",
        ],
        "ru": [
            "Анкета на визу (2 экземпляра)",
            "Загранпаспорт",
            "2 биометрических фото",
            "Диплом (должен быть признан в Германии, мин. 5 баллов по системе Chancenkarte)",
            "Lebenslauf (Europass формат)",
            "Мотивационное письмо",
            "Языковой сертификат (немецкий A1 или английский B2 — требование Chancenkarte)",
            "Подтверждение финансов (Sperrkonto)",
            "Медицинская страховка",
            "Квитанция об оплате визового сбора",
        ],
        "en": [
            "Visa application form (2 copies)",
            "Valid passport",
            "2 biometric photos",
            "Degree/diploma (must be recognized in Germany, min. 5 points under Chancenkarte system)",
            "Lebenslauf (Europass format)",
            "Motivation letter",
            "Language certificate (German A1 or English B2 — Chancenkarte requirement)",
            "Proof of financial resources (Sperrkonto)",
            "Health insurance",
            "Visa fee payment receipt",
        ],
        "tr": [
            "Vize başvuru formu (2 nüsha)",
            "Geçerli pasaport",
            "2 biyometrik fotoğraf",
            "Diploma (Almanya'da tanınmalı, Chancenkarte sistemine göre min. 5 puan)",
            "Lebenslauf (Europass formatı)",
            "Motivasyon mektubu",
            "Dil sertifikası (Almanca A1 veya İngilizce B2 — Chancenkarte gereksinimi)",
            "Mali yeterlilik kanıtı (Sperrkonto)",
            "Sağlık sigortası",
            "Vize ücreti ödeme makbuzu",
        ],
        "es": [
            "Formulario de solicitud de visa (2 copias)",
            "Pasaporte válido",
            "2 fotos biométricas",
            "Título/diploma (debe ser reconocido en Alemania, mín. 5 puntos según el sistema Chancenkarte)",
            "Lebenslauf (formato Europass)",
            "Carta de motivación",
            "Certificado de idioma (alemán A1 o inglés B2 — requisito de Chancenkarte)",
            "Comprobante de recursos financieros (Sperrkonto)",
            "Seguro médico",
            "Recibo de pago de la tasa de visa",
        ],
        "hi": [
            "वीज़ा आवेदन फ़ॉर्म (2 प्रतियां)",
            "मान्य पासपोर्ट",
            "2 बायोमेट्रिक फ़ोटो",
            "डिग्री/डिप्लोमा (जर्मनी में मान्यता प्राप्त होना चाहिए, Chancenkarte प्रणाली के तहत कम से कम 5 अंक)",
            "Lebenslauf (Europass फॉर्मेट)",
            "प्रेरणा पत्र",
            "भाषा प्रमाणपत्र (जर्मन A1 या अंग्रेज़ी B2 — Chancenkarte आवश्यकता)",
            "वित्तीय संसाधनों का प्रमाण (Sperrkonto)",
            "स्वास्थ्य बीमा",
            "वीज़ा शुल्क भुगतान रसीद",
        ],
        "uk": [
            "Анкета на візу (2 копії)",
            "Дійсний паспорт",
            "2 біометричних фото",
            "Диплом (має бути визнаний у Німеччині, мін. 5 балів за системою Chancenkarte)",
            "Lebenslauf (формат Europass)",
            "Мотиваційний лист",
            "Сертифікат мови (німецька A1 або англійська B2 — вимога Chancenkarte)",
            "Підтвердження фінансів (Sperrkonto)",
            "Медичне страхування",
            "Квитанція про оплату візового збору",
        ],
    },
    "family": {
        "uz": [
            "To'ldirilgan viza ariza formasi (2 nusxa)",
            "Xalqaro pasport",
            "2 dona biometrik fotosurat",
            "Nikoh/tug'ilganlik guvohnomasi (apostil va tarjima bilan)",
            "Germaniyadagi oila a'zosining hujjatlari (passport, ro'yxatga olinish, ish/daromad isboti)",
            "Nemis tili sertifikati (odatda A1 daraja, ba'zi holatlarda talab qilinmaydi)",
            "Tibbiy sug'urta",
            "Viza yig'imi kvitansiyasi",
        ],
        "ru": [
            "Анкета на визу (2 экземпляра)",
            "Загранпаспорт",
            "2 биометрических фото",
            "Свидетельство о браке/рождении (с апостилем и переводом)",
            "Документы члена семьи в Германии (паспорт, регистрация, подтверждение дохода)",
            "Сертификат немецкого языка (обычно A1, в некоторых случаях не требуется)",
            "Медицинская страховка",
            "Квитанция об оплате визового сбора",
        ],
        "en": [
            "Visa application form (2 copies)",
            "Valid passport",
            "2 biometric photos",
            "Marriage/birth certificate (apostilled and translated)",
            "Documents of family member in Germany (passport, registration, proof of income)",
            "German language certificate (usually A1, sometimes waived)",
            "Health insurance",
            "Visa fee payment receipt",
        ],
        "tr": [
            "Vize başvuru formu (2 nüsha)",
            "Geçerli pasaport",
            "2 biyometrik fotoğraf",
            "Evlilik/doğum belgesi (apostil ve tercüme ile)",
            "Almanya'daki aile üyesinin belgeleri (pasaport, kayıt, gelir kanıtı)",
            "Almanca dil sertifikası (genellikle A1, bazı durumlarda gerekmez)",
            "Sağlık sigortası",
            "Vize ücreti ödeme makbuzu",
        ],
        "es": [
            "Formulario de solicitud de visa (2 copias)",
            "Pasaporte válido",
            "2 fotos biométricas",
            "Certificado de matrimonio/nacimiento (apostillado y traducido)",
            "Documentos del familiar en Alemania (pasaporte, registro, comprobante de ingresos)",
            "Certificado de alemán (normalmente A1, a veces no se exige)",
            "Seguro médico",
            "Recibo de pago de la tasa de visa",
        ],
        "hi": [
            "वीज़ा आवेदन फ़ॉर्म (2 प्रतियां)",
            "मान्य पासपोर्ट",
            "2 बायोमेट्रिक फ़ोटो",
            "विवाह/जन्म प्रमाणपत्र (एपोस्टील और अनुवादित)",
            "जर्मनी में परिवार के सदस्य के दस्तावेज़ (पासपोर्ट, पंजीकरण, आय प्रमाण)",
            "जर्मन भाषा प्रमाणपत्र (सामान्यतः A1, कभी-कभी आवश्यक नहीं)",
            "स्वास्थ्य बीमा",
            "वीज़ा शुल्क भुगतान रसीद",
        ],
        "uk": [
            "Анкета на візу (2 копії)",
            "Дійсний паспорт",
            "2 біометричних фото",
            "Свідоцтво про шлюб/народження (з апостилем і перекладом)",
            "Документи члена сім'ї в Німеччині (паспорт, реєстрація, підтвердження доходу)",
            "Сертифікат німецької мови (зазвичай A1, іноді не вимагається)",
            "Медичне страхування",
            "Квитанція про оплату візового збору",
        ],
    },
}


def get_checklist(visa_type: str, lang: str) -> list[str]:
    """Berilgan viza turi va til uchun hujjatlar ro'yxatini qaytaradi."""
    return CHECKLISTS.get(visa_type, {}).get(lang, CHECKLISTS.get(visa_type, {}).get("en", []))
